/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nissan-skyline-gt500-wwwvecarzcom-0e24a69df7384890b59132005ec6c331
Title: Nissan Skyline GT500 | www.vecarz.com
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('/nissan_skyline_gt500__www.vecarz.com.glb')
  return (
    <group {...props} dispose={null} scale={0.9} position={[0,-0.5,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.795, 1.292, 0.342]} rotation={[0, 0.035, 0]}>
          <group position={[0.001, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['outer_rim-material'].geometry}
              material={materials.outer_rim}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['wheel_black-material'].geometry}
              material={materials.wheel_black}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['inner_rim-material'].geometry}
              material={materials.inner_rim}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tyre_fx-material'].geometry}
              material={materials.tyre_fx}
              position={[0.031, 0, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
          </group>
          <group position={[-0.022, 0, 0]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['rotor-material'].geometry}
              material={materials.rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['hub-material'].geometry}
              material={materials.material_11}
            />
          </group>
          <group position={[-0.152, 0, 0]} scale={0.72}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['blur_lip-material'].geometry}
              material={materials.blur_lip}
              position={[0.135, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['rim-material'].geometry}
            material={materials.material}
            position={[-0.149, 0, 0]}
          />
        </group>
        <group position={[0.795, 1.292, 0.342]} rotation={[0, -0.035, 0]}>
          <group position={[-0.001, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['outer_rim-material_1'].geometry}
              material={materials.outer_rim}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['wheel_black-material_1'].geometry}
              material={materials.wheel_black}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['inner_rim-material_1'].geometry}
              material={materials.inner_rim}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tyre_fx-material_1'].geometry}
              material={materials.tyre_fx}
              position={[-0.031, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[0.022, 0, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['rotor-material_1'].geometry}
              material={materials.rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['hub-material_1'].geometry}
              material={materials.material_11}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['rim-material_1'].geometry}
            material={materials.material}
            position={[0.149, 0, 0]}
          />
          <group position={[0.152, 0, 0]} scale={0.72}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['blur_lip-material_1'].geometry}
              material={materials.blur_lip}
              position={[-0.135, 0, 0]}
              rotation={[0, 0, -Math.PI]}
            />
          </group>
        </group>
        <group position={[0.795, -1.378, 0.342]} rotation={[0, -0.052, 0]}>
          <group position={[-0.001, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['outer_rim-material_2'].geometry}
              material={materials.outer_rim}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['wheel_black-material_2'].geometry}
              material={materials.wheel_black}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['inner_rim-material_2'].geometry}
              material={materials.inner_rim}
              position={[0.055, 0, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tyre_fx-material_2'].geometry}
              material={materials.tyre_fx}
              position={[-0.031, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[0.025, 0, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['rotor-material_2'].geometry}
              material={materials.rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['hub-material_2'].geometry}
              material={materials.material_11}
            />
          </group>
          <group position={[0.152, 0, 0]} scale={0.72}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['blur_lip-material_2'].geometry}
              material={materials.blur_lip}
              position={[-0.135, 0, 0]}
              rotation={[0, 0, -Math.PI]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['rim-material_2'].geometry}
            material={materials.material}
            position={[0.149, 0, 0]}
          />
        </group>
        <group position={[-0.795, -1.378, 0.342]} rotation={[0, 0.052, 0]}>
          <group position={[0.001, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tyre_fx-material_3'].geometry}
              material={materials.tyre_fx}
              position={[0.031, 0, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['outer_rim-material_3'].geometry}
              material={materials.outer_rim}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['wheel_black-material_3'].geometry}
              material={materials.wheel_black}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['inner_rim-material_3'].geometry}
              material={materials.inner_rim}
              position={[-0.055, 0, 0]}
              scale={0.72}
            />
          </group>
          <group position={[-0.026, 0, 0]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['rotor-material_3'].geometry}
              material={materials.rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['hub-material_3'].geometry}
              material={materials.material_11}
            />
          </group>
          <group position={[-0.152, 0, 0]} scale={0.72}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['blur_lip-material_3'].geometry}
              material={materials.blur_lip}
              position={[0.135, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['rim-material_3'].geometry}
            material={materials.material}
            position={[-0.149, 0, 0]}
          />
        </group>
        <group position={[0.795, -1.378, 0.342]} rotation={[0, -0.052, 0]}>
          <group position={[0.025, 0, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['caliper-material'].geometry}
              material={materials.caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['badge-material'].geometry}
              material={materials.badge}
            />
          </group>
        </group>
        <group position={[-0.795, -1.378, 0.342]} rotation={[0, 0.052, 0]}>
          <group position={[-0.026, 0, 0]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['caliper-material_1'].geometry}
              material={materials.caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['badge-material_1'].geometry}
              material={materials.badge}
            />
          </group>
        </group>
        <group position={[-0.795, 1.292, 0.342]} rotation={[0, 0.035, 0]}>
          <group position={[-0.022, 0, 0]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['caliper-material_2'].geometry}
              material={materials.caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['badge-material_2'].geometry}
              material={materials.badge}
            />
          </group>
        </group>
        <group position={[0.795, 1.292, 0.342]} rotation={[0, -0.035, 0]}>
          <group position={[0.022, 0, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['caliper-material_3'].geometry}
              material={materials.caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['badge-material_3'].geometry}
              material={materials.badge}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['chrome-material'].geometry}
          material={materials.chrome}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['frame-material'].geometry}
          material={materials.frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['matte_colors-material'].geometry}
          material={materials.matte_colors}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['misc-material'].geometry}
          material={materials.misc}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material'].geometry}
          material={materials.glass}
          position={[0, 0, 0.022]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_1'].geometry}
          material={materials.glass}
          position={[0, 0, 0.049]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_2'].geometry}
          material={materials.glass}
          position={[0, 0, 0.045]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_1'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.material_0}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['rubber_trim-material'].geometry}
          material={materials.rubber_trim}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_2'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.material_0}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['rubber_trim-material_1'].geometry}
          material={materials.rubber_trim}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_3'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_4'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['emblem-material'].geometry}
          material={materials.emblem}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['frame-material_1'].geometry}
          material={materials.frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_1'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_2'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['reflector-material'].geometry}
          material={materials.reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['rubber_trim-material_2'].geometry}
          material={materials.rubber_trim}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['tail_light_lod0-material'].geometry}
          material={materials.tail_light_lod0}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['textured_reflector-material'].geometry}
          material={materials.textured_reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_3'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_4'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_5'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_5'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_6'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['emblem-material_1'].geometry}
          material={materials.emblem}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['frame-material_2'].geometry}
          material={materials.frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['grille1_alpha-material'].geometry}
          material={materials.grille1_alpha}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['matte_colors-material_1'].geometry}
          material={materials.matte_colors}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_7'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bumper_frame-material'].geometry}
          material={materials.bumper_frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bumper_frame-material_1'].geometry}
          material={materials.bumper_frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_8'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_6'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bottom_001-material'].geometry}
          material={materials['bottom.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['frame-material_3'].geometry}
          material={materials.frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['matte_colors-material_2'].geometry}
          material={materials.matte_colors}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['misc-material_1'].geometry}
          material={materials.misc}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['black-material'].geometry}
          material={materials.black}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['head_light-material'].geometry}
          material={materials.head_light}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['reflector-material_1'].geometry}
          material={materials.reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['textured_reflector-material_1'].geometry}
          material={materials.textured_reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['black-material_1'].geometry}
          material={materials.black}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['head_light-material_1'].geometry}
          material={materials.head_light}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['reflector-material_2'].geometry}
          material={materials.reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['textured_reflector-material_2'].geometry}
          material={materials.textured_reflector}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_3'].geometry}
          material={materials.glass}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_4'].geometry}
          material={materials.glass}
          position={[0, 0, 0.035]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_amber-material'].geometry}
          material={materials.detail_glass_amber}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_red-material'].geometry}
          material={materials.detail_glass_red}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_5'].geometry}
          material={materials.glass}
          position={[0, 0, 0.038]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_6'].geometry}
          material={materials.glass}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['glass-material_7'].geometry}
          material={materials.glass}
          position={[0, 0, 0.035]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_amber-material_1'].geometry}
          material={materials.detail_glass_amber}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_red-material_1'].geometry}
          material={materials.detail_glass_red}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_7'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['chrome-material_1'].geometry}
          material={materials.chrome}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['emblem-material_2'].geometry}
          material={materials.emblem}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['frame-material_4'].geometry}
          material={materials.frame}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['grille1-material'].geometry}
          material={materials.grille1}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['matte_colors-material_3'].geometry}
          material={materials.matte_colors}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['misc-material_2'].geometry}
          material={materials.misc}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['plastic2-material'].geometry}
          material={materials.plastic2}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_9'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['body-material_8'].geometry}
          material={materials.body}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['misc-material_3'].geometry}
          material={materials.misc}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_10'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['headliner-material'].geometry}
          material={materials.headliner}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_11'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material_001-material_12'].geometry}
          material={materials['Material.001']}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_red-material_2'].geometry}
          material={materials.detail_glass_red}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['detail_glass_red-material_3'].geometry}
          material={materials.detail_glass_red}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['tail_light_lod0-material_1'].geometry}
          material={materials.tail_light_lod0}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['tail_light_lod0-material_2'].geometry}
          material={materials.tail_light_lod0}
          position={[0, 0, 0.032]}
          rotation={[0, 0, Math.PI]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/nissan_skyline_gt500__www.vecarz.com.glb')



