/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/helicopter_space_ship.glb -o src/components/Helecopter.jsx -r public 
Author: VertaScan (https://sketchfab.com/VertaScan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/helicopter-space-ship-0a33ff169e3144ffb3e10dd751454296
Title: Helicopter Space Ship
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Helecopter(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/helicopter_space_ship.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[-0.1,0,-2]}  scale={ 0.2 }>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -6.7]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="CHASSIS_0" position={[0, 1.797, -0.06]} rotation={[0.037, 0, 0]} scale={[0.825, 0.888, 5.201]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.MESH_MAT} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cube007_1" position={[0, 1.797, -0.06]} rotation={[0.037, 0, 0]} scale={[0.825, 0.888, 5.201]}>
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.WINDSHIELD} />
              </group>
              <group name="Cylinder_2" position={[-2.015, 3.545, -0.254]} rotation={[1.607, 0, 0]} scale={[0.37, 1.056, 0.312]}>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Cylinder002_3" position={[-2.856, 3.518, -0.629]} rotation={[1.607, 0, 0]} scale={[0.493, 0.599, 0.416]}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.EXT_MESH} />
              </group>
              <group name="Torus_4" position={[-5.005, 3.719, -0.655]} rotation={[0.037, 0, 0]} scale={[1.35, 1.141, 1.35]}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Torus001_5" position={[-5.005, 3.723, -0.659]} rotation={[0.037, 0, 0]} scale={[1.35, 1.141, 1.35]}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.EXT_MESH} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.ENGINE} />
              </group>
              <group name="Cylinder008_8" position={[-3.415, 2.377, -2.207]} rotation={[Math.PI / 2, 0, 0]} scale={[0.185, 0.93, 0.17]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.ENGINE} />
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder010_9" position={[-3.415, 2.234, -4.398]} rotation={[-2.32, 0, 0]} scale={[0.105, 0.279, 0.096]}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.ENGINE} />
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cube012_11" position={[0, 1.797, -0.06]} rotation={[0.037, 0, 0]} scale={[0.825, 0.888, 5.201]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="CHASIS_13" position={[0, 1.797, -0.06]} rotation={[0.037, 0, 0]} scale={[0.825, 0.888, 5.201]}>
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.MESH_2} />
              </group>
              <group name="Sphere002_14" position={[3.356, 3.662, -0.629]} scale={0.17}>
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.EXT_MESH} />
              </group>
              <group name="Torus004_15" position={[5.005, 3.723, -0.659]} rotation={[0.037, 0, 0]} scale={[1.35, 1.141, 1.35]}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.EXT_MESH} />
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.ENGINE} />
              </group>
              <group name="Torus005_16" position={[5.005, 3.719, -0.655]} rotation={[0.037, 0, 0]} scale={[1.35, 1.141, 1.35]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Sphere003_17" position={[-3.344, 3.662, -0.629]} scale={0.17}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.EXT_MESH} />
              </group>
              <group name="Cylinder009_18" position={[-2.856, 3.524, -0.841]} rotation={[1.607, 0, 0]} scale={[0.408, 1.165, 0.344]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Cylinder011_19" position={[2.856, 3.518, -0.629]} rotation={[1.607, 0, 0]} scale={[0.408, 1.165, 0.344]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Cylinder012_20" position={[2.015, 3.541, -0.13]} rotation={[1.607, 0, 0]} scale={[0.37, 1.056, 0.312]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.MESH_MAT} />
              </group>
              <group name="Cylinder015_21" position={[2.856, 3.518, -0.629]} rotation={[1.607, 0, 0]} scale={[0.493, 0.599, 0.416]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.EXT_MESH} />
              </group>
              <group name="Cylinder018_24" position={[3.415, 2.191, -3.61]} rotation={[-2.32, 0, 0]} scale={[0.105, 0.279, 0.096]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.ENGINE} />
                <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder019_25" position={[3.415, 2.377, -2.53]} rotation={[Math.PI / 2, 0, 0]} scale={[0.185, 0.93, 0.17]}>
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.ENGINE} />
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.LIGHTS} />
              </group>
              <group name="CHASIS003_27" position={[0, 1.797, -0.06]} rotation={[0.037, 0, 0]} scale={[0.825, 0.888, 5.201]}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.MESH_2} />
              </group>
              <group name="Cylinder006_6" position={[1.615, 2.831, 0.27]} rotation={[1.607, 0, 0]} scale={[0.116, 0.331, 0.098]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.EXT_MESH} />
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder007_7" position={[-3.415, 2.973, -5.121]} rotation={[1.857, 0, 0]} scale={[0.37, 1.044, 0.317]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.ENGINE} />
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder013_10" position={[1.895, 2.865, 0.27]} rotation={[1.607, 0, 0]} scale={[0.072, 0.206, 0.061]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.EXT_MESH} />
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Object_2_Object_0_12" position={[0.007, 1.624, 2.884]} rotation={[Math.PI / 2, 0, 0]} scale={2.563}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.leather} />
              </group>
              <group name="Cylinder016_22" position={[1.312, 1.782, 0.628]} rotation={[Math.PI / 2, 0, 0]} scale={[0.211, 0.603, 0.178]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.ENGINE} />
                <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder017_23" position={[-1.312, 1.782, 0.628]} rotation={[Math.PI / 2, 0, 0]} scale={[0.211, 0.603, 0.178]}>
                <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.ENGINE} />
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Cylinder020_26" position={[3.415, 2.681, -4.13]} rotation={[1.857, 0, 0]} scale={[0.37, 1.044, 0.317]}>
                <mesh name="Object_68"  geometry={nodes.Object_68.geometry} material={materials.ENGINE} />
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.LIGHTS}  />
              </group>
              <group name="Cylinder021_28" position={[0.392, 1.172, 5.628]} rotation={[Math.PI / 2, 0, 0]} scale={[0.026, 0.334, 0.022]}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.EXT_MESH} />
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.LIGHTS} />
              </group>
              <group name="Plane_29" position={[0, -0.013, 0.771]} scale={[1, 1, 3.602]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.FLOOR} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/helicopter_space_ship.glb')
